### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by YXWisaboy** [dengxiuqi/ELMoNER#3]
看到您已经用能让人类看懂的方式把网络简单复现了，很感谢！
但是，据我所知，ELMO需要先进行大数据集的预训练，之后才能被用于NER任务中，
我没有在您代码中看到预训练的部分，您好象直接把这个网络用于实体预测了，
不知是否是我疏漏了 请指教

**Comment by dengxiuqi** [comment]
感谢认可！
因为我写这个工程的目的主要是复现网络，确实没有预训练，从头开始训练整个模型。
